format = "$sudo$directory$git_branch$git_status $character"
right_format = "$golang$php$nodejs$swift$docker_context$package$jobs$cmd_duration$battery"

palette = "catppuccin_mocha"

[directory]
style = "bold blue" 
format = "[$path]($style)"
truncation_length = 0
truncate_to_repo = false
read_only = " ï€£"

[cmd_duration]
min_time = 2000        # Show if command took > 2000 ms (2 s)
show_milliseconds = false
format = "â± [$duration]($style) "
style = "bold yellow"

[character]
success_symbol = "â¯"
error_symbol = "[â¯](bold red)"

[git_branch]
symbol = "î‚ "
style = "bold teal"
format = ' [(\($symbol $branch\))]($style)'

[git_status]
format = " [($all_status$ahead_behind)]($style)"
style = "red"
conflicted = "âš”"
ahead = "â‡¡"
behind = "â‡£"
diverged = "â‡•"
untracked = "?"
stashed = "ğŸ“¦"
modified = "~"
staged = "+"
renamed = "Â»"
deleted = "âœ˜"

[battery]
format = "[ $percentage $symbol]($style)"
full_symbol = "â–ˆ"
charging_symbol = "[â†‘](italic bold green)"
discharging_symbol = "â†“"
unknown_symbol = "â–‘"
empty_symbol = "â–ƒ"

[[battery.display]]
threshold = 20
style = "italic bold red"


########################################
# Languages
########################################

[golang]
symbol = "î˜§ "
style = "bold sky"  # sky blue (Catppuccin blue)
format = " [$symbol($version)]($style)"

[nodejs]
symbol = "îœ˜ "
style = "green"
format = ' [$symbol($version)]($style)'

[php]
symbol = "î˜ˆ "
style = "lavender"
format = ' [$symbol($version)]($style)'

[swift]
symbol = "î• "
style = "red"
format = ' [$symbol($version)]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "teal"
format = ' [$symbol$context]($style)'
only_with_files = true

[c]
symbol = "î˜ "
style = "sky"
format = " [$symbol($version)]($style)"

[java]
symbol = "î‰– "
style = "peach"
format = " [$symbol($version)]($style)"

[python]
symbol = "îˆµ "
style = "yellow"
format = " [$symbol($version)]($style)"

[rust]
symbol = "îš‹ "
style = "maroon"
format = " [$symbol($version)]($style)"

[jobs]
symbol = "ï‚… "
style = "yellow"
format = " [$symbol$number]($style)"

[package]
disabled = false
symbol = "ï£– "
style = "teal"
format = " [$symbol$version]($style)"

########################################
# Catppuccin Mocha Palette
########################################
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo  = "#f2cdcd"
pink      = "#f5c2e7"
mauve     = "#cba6f7"
red       = "#f38ba8"
maroon    = "#eba0ac"
peach     = "#fab387"
yellow    = "#f9e2af"
green     = "#a6e3a1"
teal      = "#94e2d5"
sky       = "#89dceb"
sapphire  = "#74c7ec"
blue      = "#89b4fa"
lavender  = "#b4befe"
text      = "#cdd6f4"
subtext1  = "#bac2de"
subtext0  = "#a6adc8"
overlay2  = "#9399b2"
overlay1  = "#7f849c"
overlay0  = "#6c7086"
surface2  = "#585b70"
surface1  = "#45475a"
surface0  = "#313244"
base      = "#1e1e2e"
mantle    = "#181825"
crust     = "#11111b"
