---
- name: Setup Dotfiles
  hosts: all
  roles:
    - { role: dotfiles, tags: [setup] }
    - { role: homebrew, tags: [setup,homebrew,brew] }
    - { role: iterm, tags: [setup,iterm] }
    - { role: fonts, tags: [setup,fonts] }