dotfiles:
  - { src: '{{ playbook_dir }}/../config/zsh/.zshrc', dest: '{{ ansible_env.HOME }}/.zshrc' }
  - { src: '{{ playbook_dir }}/../config/zsh/.zprofile', dest: '{{ ansible_env.HOME }}/.zprofile' }

  - { src: '{{ playbook_dir }}/../config/system/alias/.alias', dest: '{{ ansible_env.HOME }}/alias/.alias' }
  - { src: '{{ playbook_dir }}/../config/system/alias/.alias.custom', dest: '{{ ansible_env.HOME }}/alias/.custom' }
  - { src: '{{ playbook_dir }}/../config/system/alias/.alias.macos', dest: '{{ ansible_env.HOME }}/alias/.macos' }
  - { src: '{{ playbook_dir }}/../config/system/alias/.functions', dest: '{{ ansible_env.HOME }}/alias/.functions' }

  - { src: '{{ playbook_dir }}/../config/git/.gitconfig', dest: '{{ ansible_env.HOME }}/.gitconfig' }
  - { src: '{{ playbook_dir }}/../config/git/.gitignore_global', dest: '{{ ansible_env.HOME }}/.gitignore_global' }
  - { src: '{{ playbook_dir }}/../config/tmux/.tmux.conf', dest: '{{ ansible_env.HOME }}/.tmux.conf' }
  - { src: '{{ playbook_dir }}/../config/neovim/nvim', dest: '{{ ansible_env.HOME }}/.config/nvim' }
  - { src: '{{ playbook_dir }}/../config/bat', dest: '{{ ansible_env.HOME }}/.config/bat' } 

dotfiles_path: "{{ playbook_dir }}/../config"
dotfiles_backup_path: "{{ ansible_env.HOME }}/.dotfiles_backup"