dotfiles:
  # Zsh config
  - {
      src: "{{ playbook_dir }}/../config/zsh/.zshrc",
      dest: "{{ ansible_env.HOME }}/.zshrc",
    }
  - {
      src: "{{ playbook_dir }}/../config/zsh/.zprofile",
      dest: "{{ ansible_env.HOME }}/.zprofile",
    }

    # Alias
  - {
      src: "{{ playbook_dir }}/../config/system/alias",
      dest: "{{ ansible_env.HOME }}/.alias",
    }

    # Git
  - {
      src: "{{ playbook_dir }}/../config/git/.gitconfig",
      dest: "{{ ansible_env.HOME }}/.gitconfig",
    }
  - {
      src: "{{ playbook_dir }}/../config/git/.gitignore_global",
      dest: "{{ ansible_env.HOME }}/.gitignore_global",
    }

  # --- Some more stuff
  - {
      src: "{{ playbook_dir }}/../config/wezterm",
      dest: "{{ ansible_env.HOME }}/.config/wezterm",
    }

  - {
      src: "{{ playbook_dir }}/../config/tmux",
      dest: "{{ ansible_env.HOME }}/.config/tmux",
    }

  - {
      src: "{{ playbook_dir }}/../config/neovim/nvim",
      dest: "{{ ansible_env.HOME }}/.config/nvim",
    }
  - {
      src: "{{ playbook_dir }}/../config/bat",
      dest: "{{ ansible_env.HOME }}/.config/bat",
    }
  - {
      src: "{{ playbook_dir }}/../config/lazygit",
      dest: "{{ ansible_env.HOME }}/.config/lazygit",
    }
  - {
      src: "{{ playbook_dir }}/../config/starship/starship.toml",
      dest: "{{ ansible_env.HOME }}/.config/starship.toml",
    }
  - {
      src: "{{ playbook_dir }}/../config/aerospace",
      dest: "{{ ansible_env.HOME }}/.config/aerospace",
    }
  - {
      src: "{{ playbook_dir }}/../config/sketchybar",
      dest: "{{ ansible_env.HOME }}/.config/sketchybar",
    }
  - {
      src: "{{ playbook_dir }}/../config/borders",
      dest: "{{ ansible_env.HOME }}/.config/borders",
    }
  - {
      src: "{{ playbook_dir }}/../config/opencode",
      dest: "{{ ansible_env.HOME }}/.config/opencode",
    }

dotfiles_path: "{{ playbook_dir }}/../config"
dotfiles_backup_path: "{{ ansible_env.HOME }}/.dotfiles_backup"
